--- 
logsBucket: "gs://container_build_logs_tm"
steps: 
  - 
    args: 
      - build
      - "--tag"
      - $_REPO/$PROJECT_ID/$_DOCKER_TAG_DATE_COMMIT
      - "--tag"
      - $_REPO/$PROJECT_ID/$_DOCKER_TAG_COMMIT
      - "--build-arg"
      - PIP_EXTRA_INDEX_URL=$_PIP_EXTRA_INDEX_URL
      - "."
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - build
      - "--tag"
      - $_REPO/$PROJECT_ID/py3-$_DOCKER_TAG_DATE_COMMIT
      - "--tag"
      - $_REPO/$PROJECT_ID/py3-$_DOCKER_TAG_COMMIT
      - "--build-arg"
      - PIP_EXTRA_INDEX_URL=$_PIP_EXTRA_INDEX_URL
      - "--target"
      - python3_run
      - "."
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - push
      - $_REPO/$PROJECT_ID/$_SERVICE
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - container
      - images
      - add-tag
      - $_REPO/$PROJECT_ID/$_DOCKER_TAG_DATE_COMMIT
      - $_REPO/$PROJECT_ID/$_DOCKER_TAG_COMMIT
      - "-q"
    name: gcr.io/cloud-builders/gcloud
