version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

jobs:
  build:
    working_directory: ~/hackathon-counters
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          # Disable any of the interactive prompts
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
          DEBIAN_FRONTEND: noninteractive
          GOOGLE_COMPUTE_ZONE: us-central1-a
          GOOGLE_PROJECT_ID: triggeredmail
    steps:
      - checkout

      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t app .

      # Install but don't authenticate the Google Cloud tools
      - gcp-cli/install
      - gcp-cli/initialize:
          gcloud-service-key: GCLOUD_ACCOUNT_CRED

      - run: |
          echo $GCLOUD_ACCOUNT_CRED > gcr_key.json
          cat gcr_key.json | docker login -u _json_key --password-stdin https://us.gcr.io

      - run: |
          echo '---'
          echo 'Pushing the docker images ...'
          echo '---'
          export IMAGE_VERSION_TAG=us.gcr.io/triggeredmail/hackathon-counters:{CIRCLE_BUILD_NUM}
          docker tag app $IMAGE_VERSION_TAG
          docker push $IMAGE_VERSION_TAG
