version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
        DATABASE_URL: postgresql+pg8000://postgres:@localhost/test
        # Disable any of the interactive prompts
        CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
